image: elixir:1.11.1-alpine

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

mix:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - _build
      - deps
      - priv/plts
  script:
    - mix dialyzer
    - mix test
  tags:
    - docker
